config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :users, only: [:show] do
    resources :subscriptions, except: [:edit, :update]
  end
  namespace :api do
    namespace :v1 do
      resources :comics, only: [:index] do
        resources :users
      end
    end
  end

  resources :comics, except:[:destroy] do
    resources :subscriptions, except: [:edit, :update]
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :comics, only: [:new, :edit, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates :publisher, presence: true
  validates :title, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :comic
  belongs_to :user
end

app/models/user.rb
require 'uri'
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :subscriptions
  has_many :comics, through: :subscriptions

  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  after_create :send_welcome_email

  def self.weekly_reminder
    @user = User.all
    @user.each do |u|
      @name = u.first_name
      @email = u.email
      UserMailer.weekly_email(@email).deliver_later
    end
  end
  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < ApplicationController
  def new
    @comic = Comic.new
  end
  def edit
    @comic = Comic.find(params[:id])
  end
  def destroy
    if current_user.admin?
      @comic = Comic.find(params[:id])
      @comic.destroy
      redirect_to comics_path
      flash[:notice] = "Successfully deleted comic"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.admin?
      @user.destroy
      flash[:notice] = "User account deleted"
      redirect_to admin_users_path
    end
  end
end

app/controllers/api/v1/comics_controller.rb
class Api::V1::ComicsController < ApplicationController
  def index
    render json: { comics: Comic.all }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :email, :avatar])
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @title = "AVAILABLE COMICS"
    @comics = Comic.all
  end

  def create
    @comic = Comic.new(comic_params)
    if @comic.save
      redirect_to comic_path(@comic)
      flash[:notice]="Successfully added comic"
    else
      flash[:notice] = @comic.errors.full_messages.to_sentence
      render "admin/comics/new"
    end
  end

  def show
    @comic = Comic.find(params[:id])
    @user = current_user
    @subscription = Subscription.find_by(user: @user, comic: @comic)
  end

  def update
    @comic = Comic.find(params[:id])
    if @comic.update_attributes(comic_params)
      flash[:notice] = "Comic Updated"
      redirect_to comic_path(@comic)
    else
      flash[:notice] = @comic.errors.full_messages.to_sentence
      render "admin/comics/edit"
    end
  end

  private

  def comic_params
    params.require(:comic).permit(:publisher, :title, :writer, :artist, :main_character, :other_characters, :photo, :keywords, :ongoing)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cap_marvel = Comic.find_by(title: "Captain Marvel (2016 - Present)")
    @ironman = Comic.find_by(title: "Iron Man Annual (1970 - 1994)")
    @black_panther = Comic.find_by(title: "Black Panther (2016 - Present)")
    @black_widow = Comic.find_by(title: "Black Widow (2010)")
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @user = current_user
    @comics = @user.comics
    @title = "#{@comics.length} CURRENT SUBSCRIPTION(S):"
  end
  def new
    @subscription = Subscription.new
    @comic = Comic.find(params[:comic_id])
  end
  def create
    @comic = Comic.find(params[:comic_id])
    @subscription = Subscription.create(user: current_user, comic: @comic)
    redirect_to user_subscriptions_path(current_user)
  end
  def destroy
    @comic = Comic.find(params[:comic_id])
    @user = current_user
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    redirect_to user_path(@user)
    flash[:notice] = "Subscription ended"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/comics/edit.html.erb
<h2 class="page-title"> Edit Comic </h2>
<div class="row">
  <div class="large-6 small-12 columns">
    <%= form_for @comic do |f| %>
      <%= f.label :publisher, "Publisher: " %>
      <%= f.text_field :publisher %>
      </br>
      <%= f.label :title, "Title: " %>
      <%= f.text_field :title %>
      </br>
      <%= f.label :writer, "Writer: " %>
      <%= f.text_area :writer %>
      </br>
      <%= f.label :artist, "Artist: " %>
      <%= f.text_area :artist %>
      </br>
      <%= f.label :main_character, "Main Character: " %>
      <%= f.text_area :main_character %>
      </br>
      <%= f.label :other_characters, "Other Character(s): " %>
      <%= f.text_area :other_characters %>
      </br>
      <%= f.label :ongoing, "Currently Ongoing", value: true %>
      <%= f.radio_button :ongoing, true %>
      </br>
      <%= f.label :ongoing, "Series Ended", value: false %>
      <%= f.radio_button :ongoing, false %>
      </br>
      <%= f.submit "Submit Changes", class:"form-button"  %>
    <% end %>
  </div>
</div>

app/views/admin/comics/new.html.erb
<h2 class="page-title"> Add Comic </h2>
<div class="row">
  <div class="large-6 small-12 columns">
    <%= form_for @comic do |f| %>
      <%= f.label :publisher, "Publisher: " %>
      <%= f.text_field :publisher %>
      </br>
      <%= f.label :title, "Title: " %>
      <%= f.text_field :title %>
      </br>
      <%= f.label :writer, "Writer: " %>
      <%= f.text_area :writer %>
      </br>
      <%= f.label :artist, "Artist: " %>
      <%= f.text_area :artist %>
      </br>
      <%= f.label :main_character, "Main Character: " %>
      <%= f.text_area :main_character %>
      </br>
      <%= f.label :other_characters, "Other Character(s): " %>
      <%= f.text_area :other_characters %>
      </br>
      <%= f.submit "Add Comic", class:"form-button" %>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<h3 class="page-title row"> All Users </h3>
<div class="row" id="user-index">
<% @users.each do |user| %>
  <div class="row user-block" id="<%= user.id %>">
    <img src="<%=user.avatar%>" class="user-photo row" height="80" width="100">
    <div class="row">
      <div class="large-6 small-12 columns user-info">
        </br>
        Name: <%= user.first_name %> <%= user.last_name %>
        </br>
        Username: <%= user.username %>
        </br>
        Email: <%= user.email %>
        </br>
      </div>
      <div class="large-6 small-12 columns">
      </br>
        <ul class="sub-list"> Subscriptions:
          <% user.comics.each do |comic|%>
            <li><%= comic.title %></li>
            <% end %>
        </ul>
      </div>
    </div>
    <div>
      <%= link_to "Delete User", admin_user_path(user), method: :delete %>
    </div>
  </div>
  <div class="user-divider"></div>
<% end %>
</div>

app/views/comics/index.html.erb
<h2 class="page-title row"><%= @title %></h2>
<div id='app' class="row">
</div>

app/views/comics/show.html.erb
<div class="comics-show">
  <h2 class="page-title"><%= @comic.title %></h2>
  <% if @comic.photo %>
    </br>
    <div class="comic-photo">
      <img src="<%=@comic.photo %>">
    </div>
    </br>
  <% end %>
  <%= @comic.publisher %>
  <% if @comic.writer && @comic.artist %>
    <li>
      <ul>
        Creators:
        <li>Writer:
          <%= @comic.writer %>
        </li>
        <li>Artist:
          <%= @comic.artist %>
        </li>
      </ul>
    </li>
  <% end %>
  <% if @comic.main_character %>
    <li>
      Main Character: <%= @comic.main_character %>
    </li>
  <% end %>
  <% if @comic.other_characters %>
    <li>
      Other Character(s): <%= @comic.other_characters %>
    </li>
  <% end %>
  <% if @comic.ongoing? %>
    <p>Ongoing: TRUE</p>
  <% else %>
    <p>Ongoing: FALSE</p>
  <% end %>
  <% if current_user %>
    <% if !@user.comics.include?(@comic)%>
      <%= link_to "Add Subscription", comic_subscriptions_path(@comic), method: :post %>
    <% elsif @user.comics.include?(@comic) %>
      <%= link_to "End Subscription", comic_subscription_path(@comic, @subscription), method: :delete %>
    <% end %>
    <% if current_user.try(:admin?) %>
      <p>
        <%= link_to "Delete Comic", admin_comic_path(@comic), method: :delete %> |
        <%= link_to "Edit Comic", edit_admin_comic_path(@comic) %>
      </p>
    <% end %>
  <% end %>
</div>
</br>
<div class="react-footer">
  <a href="http://marvel.com" class="attribution">Data provided by Marvel. © 2014 Marvel</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicZone</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Dosis|Droid+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav>
      <div class="top-bar">
        <div class="top-bar-left">
          <h1 class="menu-text">
            <%= link_to "ComicZone!", comics_path %>
          </h1>
        </div>
        <div class="top-bar-right">
          <ul class="menu">
            <% if user_signed_in? %>
              <% if current_user.avatar.present? %>
                <li class="profile-picture">
                  <img src="<%=current_user.avatar%>" height=40 width=40>
                </li>
              <% end %>
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
          <% if current_user.try(:admin?) %>
            <ul class="menu">
              <li><%= link_to "View Users", admin_users_path %></li>
              <li><%= link_to "Update Comics", comics_path %></li>
              <li><%= link_to "Add Comic", new_admin_comic_path %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <div id="outer-wrapper" class="row fullWidth">
      <div id="wrapper">
        <% flash.each do |key, value| %>
          <%= value %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1 id="splash-greeting" class="large-12 small-12 columns">Welcome to ComicZone!</h1>
<div class="row" id="splash-page">
  <%= link_to image_tag("capmarvel.jpg", alt: "Captain Marvel (2016-Present)", class: "large-3 small-12 columns splash-image"), comic_path(@cap_marvel.id) %>

  <%= link_to image_tag("ironman.jpg", alt: "Iron Man Annual (1970 - 1994)", class:"large-3 small-12 columns splash-image"), comic_path(@ironman.id)%>

  <%= link_to image_tag("blackpanther.jpg", alt: "Black Panther (2016 - Present)", class:"large-3 small-12 columns splash-image"), comic_path(@black_panther.id)%>

  <%= link_to image_tag("blackwidow.jpg", alt: "Black Widow (2010)", class:"large-3 small-12 columns splash-image"), comic_path(@black_widow.id)%>
</div>
<div class="react-footer">
  <a href="http://marvel.com" class="attribution">Data provided by Marvel. © 2014 Marvel</a>
</div>

app/views/subscriptions/index.html.erb
<div><h2 class="page-title row"><%= @title %></h2></div>
<div id="subscription-divider" class="row"></div>
<div id="subscription-menu" class="row">
  <% @comics.each do |comic| %>
    <div class="comic-link row" id="<%= comic.id %>">
      <div class="large-3 small-12 columns">
        <img src="<%= comic.photo %>" class="crop"/>
      </div>
      <div class="large-9 small-12 columns">
        <h5><%= link_to "#{comic.title}", comic_path(comic)%> </h5>
        <h5 class="comic-publisher"><%= comic.publisher %></h5>
      </div>
      </ br>
    </div>
  <% end %>
</div>
<div class="react-footer">
  <a href="http://marvel.com" class="attribution">Data provided by Marvel. © 2014 Marvel</a>
</div>

app/views/users/show.html.erb
<div class="profile-page">

  <h2 class="page-title">
    <%= @user.username %>'s Homepage
  </h2>
  <h4>Welcome, <%= @user.first_name %></h4>
  <% if @user.avatar.present? %>
    <p class="profile-picture">
      <img src="<%=@user.avatar%>" height="100" width=100>
    </p>
  <% end %>
  <%= link_to "Your Subscriptions", user_subscriptions_path(@user) %>
  <br />
  <%= link_to "Add More Subscriptions!", comics_path %>
</div>